parameter_defaults:
  ControllerSchedulerHints:
    'capabilities:node': 'controller-%index%'
  NovaComputeSchedulerHints:
    'capabilities:node': 'novacompute-%index%'
  CephStorageSchedulerHints:
    'capabilities:node': 'cephstorage-%index%'
